# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy frontend and backend app to Azure

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and zip apps from /dist
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v4
              with:
                  node-version: '18.x'

            - name: run npm install and npm build
              run: |
                  npm install
                  npm run build

            - name: Zip artifacts for deployment
              run: |
                  echo ${GITHUB_WORKSPACE}
                  cd ${GITHUB_WORKSPACE}/dist/apps/nest-app/ && zip ${GITHUB_WORKSPACE}/nest-app-master.zip ./* -r
                  cd ${GITHUB_WORKSPACE}/dist/apps/frontend/ && zip ${GITHUB_WORKSPACE}/frontend-master.zip ./* -r

            - name: Upload frontend artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: frontend
                  path: frontend-master.zip

            - name: Upload nest-app artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: nest-app
                  path: nest-app-master.zip

    deploy-frontend:
        runs-on: ubuntu-latest
        name: Deploy Angular Frontend
        needs: build
        environment:
            name: 'Production'

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: frontend

            - name: Unzip artifact for deployment
              run: unzip frontend-master.zip

            - name: Deploy to static azure web app
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  app_location: '/' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'dist/apps/frontend' # Built app content directory - optional
                  github_id_token: ${{ steps.idtoken.outputs.result }}

    deploy-nest-app:
        runs-on: ubuntu-latest
        name: Deploy NestJs nest-app backend
        needs: build
        environment:
            name: 'Production'
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: nest-app

            - name: Unzip artifact for deployment
              run: unzip nest-app-master.zip

            - name: Install dependencies
              run: npm install

            - name: 'Deploy to Azure Web App'
              id: deploy-to-webapp
              uses: azure/webapps-deploy@v3
              with:
                  app-name: 'WesselKNestJS'
                  slot-name: 'Production'
                  publish-profile: ${{ secrets.NESTJS_PUBLISHPROFILE }}
                  package: .
